// THE FIFTH STATE - challenge test suite.
//
// Copy this file to  test/challenge_test.dart  in your quote_app and run:
//     flutter test
//
// Do not edit this file. Change the app until these pass.

import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:quote_app/features/quote/data/quote_service.dart';
import 'package:quote_app/features/quote/domain/quote_model.dart';
import 'package:quote_app/features/quote/presentation/quote_providers.dart';

/// A service that answers instantly, so the tests stay fast.
class InstantQuoteService implements QuoteService {
  @override
  Future<Quote> getQuote(QuoteRequest request) async {
    if (request.year < 2000) throw Exception('Vehicle too old to insure');
    return Quote(id: 'q-test', premium: calculatePremium(request));
  }
}

const _request = QuoteRequest(
  make: 'VW',
  year: 2020,
  driverAge: 30,
  cover: Cover.comprehensive,
);

/// Builds a container whose clock we control.
ProviderContainer _container(DateTime Function() clock) {
  final c = ProviderContainer(
    overrides: [
      quoteServiceProvider.overrideWithValue(InstantQuoteService()),
      clockProvider.overrideWithValue(clock),
    ],
  );
  addTearDown(c.dispose);
  return c;
}

void main() {
  final t0 = DateTime(2026, 9, 11, 9, 0);

  test('1. QuoteExpired exists, is a QuoteState, and carries the quote', () {
    const quote = Quote(id: 'q-1', premium: 1000);
    const state = QuoteExpired(quote);
    expect(state, isA<QuoteState>());
    expect(state.quote.id, 'q-1');
  });

  test('2. the switch over QuoteState is exhaustive with five cases', () {
    String describe(QuoteState s) => switch (s) {
          QuoteIdle() => 'idle',
          QuoteLoading() => 'loading',
          QuoteLoaded() => 'loaded',
          QuoteFailed() => 'failed',
          QuoteExpired() => 'expired',
        };
    expect(describe(const QuoteIdle()), 'idle');
    expect(describe(const QuoteExpired(Quote(id: 'x', premium: 1))), 'expired');
  });

  test('3. submit still goes idle -> loading -> loaded', () async {
    final c = _container(() => t0);
    final seen = <Type>[];
    c.listen(quoteProvider, (_, n) => seen.add(n.runtimeType),
        fireImmediately: true);

    await c.read(quoteProvider.notifier).submit(_request);

    expect(seen, [QuoteIdle, QuoteLoading, QuoteLoaded]);
  });

  test('4. a quote older than 15 minutes expires', () async {
    var now = t0;
    final c = _container(() => now);

    await c.read(quoteProvider.notifier).submit(_request);
    expect(c.read(quoteProvider), isA<QuoteLoaded>());
    final loaded = (c.read(quoteProvider) as QuoteLoaded).quote;

    now = t0.add(const Duration(minutes: 16));
    c.read(quoteProvider.notifier).checkExpiry();

    final state = c.read(quoteProvider);
    expect(state, isA<QuoteExpired>());
    expect((state as QuoteExpired).quote.id, loaded.id);
  });

  test('5. a quote 5 minutes old does not expire', () async {
    var now = t0;
    final c = _container(() => now);

    await c.read(quoteProvider.notifier).submit(_request);
    now = t0.add(const Duration(minutes: 5));
    c.read(quoteProvider.notifier).checkExpiry();

    expect(c.read(quoteProvider), isA<QuoteLoaded>());
  });

  test('6. maxAge is configurable', () async {
    var now = t0;
    final c = _container(() => now);

    await c.read(quoteProvider.notifier).submit(_request);
    now = t0.add(const Duration(minutes: 2));
    c.read(quoteProvider.notifier)
        .checkExpiry(maxAge: const Duration(minutes: 1));

    expect(c.read(quoteProvider), isA<QuoteExpired>());
  });

  test('7. checkExpiry does nothing from idle or failed', () async {
    var now = t0;
    final c = _container(() => now);

    c.read(quoteProvider.notifier).checkExpiry();
    expect(c.read(quoteProvider), isA<QuoteIdle>());

    await c.read(quoteProvider.notifier).submit(
        const QuoteRequest(make: 'VW', year: 1998, driverAge: 30, cover: Cover.comprehensive));
    expect(c.read(quoteProvider), isA<QuoteFailed>());

    now = t0.add(const Duration(hours: 2));
    c.read(quoteProvider.notifier).checkExpiry();
    expect(c.read(quoteProvider), isA<QuoteFailed>());
  });

  test('8. reset returns to idle from expired', () async {
    var now = t0;
    final c = _container(() => now);

    await c.read(quoteProvider.notifier).submit(_request);
    now = t0.add(const Duration(minutes: 30));
    c.read(quoteProvider.notifier).checkExpiry();
    expect(c.read(quoteProvider), isA<QuoteExpired>());

    c.read(quoteProvider.notifier).reset();
    expect(c.read(quoteProvider), isA<QuoteIdle>());
  });

  test('9. a fresh submit after expiry loads again', () async {
    var now = t0;
    final c = _container(() => now);

    await c.read(quoteProvider.notifier).submit(_request);
    now = t0.add(const Duration(minutes: 20));
    c.read(quoteProvider.notifier).checkExpiry();
    expect(c.read(quoteProvider), isA<QuoteExpired>());

    await c.read(quoteProvider.notifier).submit(_request);
    expect(c.read(quoteProvider), isA<QuoteLoaded>());

    // the clock restarted with the new quote
    now = now.add(const Duration(minutes: 5));
    c.read(quoteProvider.notifier).checkExpiry();
    expect(c.read(quoteProvider), isA<QuoteLoaded>());
  });
}
